---
# https://hub.docker.com/r/pihole/pihole
version: "3"
# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    secrets:
      - pihole_webpw
    environment:
      TZ: 'Europe/Madrid'
      WEBPASSWORD_FILE: '/run/secrets/pihole_webpw'
    # Volumes store your data between container upgrades
    volumes:
      - 'pihole-data:/etc/pihole'
      - 'dnsmasq-data:/etc/dnsmasq.d'
    restart: unless-stopped

volumes:
  pihole-data:
  dnsmasq-data:

secrets:
  pihole_webpw:
    file: '/var/opt/pihole/pihole_webpw'